import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable} w-[100%] h-[100%]`}>
      <body className="flex size-full flex-col items-center justify-center">
      <div className="size-full absolute bg-dbackground bg-cover z-[-10]"></div>
      {children}
      </body>
    </html>
  );
}
